<template><div><h1 id="introduction" tabindex="-1"><a class="header-anchor" href="#introduction"><span>Introduction</span></a></h1>
<p>VuePress is composed of two parts: a <a href="https://github.com/vuejs/vuepress/tree/master/packages/%40vuepress/core" target="_blank" rel="noopener noreferrer">minimalistic static site generator</a> with a Vue-powered <a href="https://v1.vuepress.vuejs.org/theme/" target="_blank" rel="noopener noreferrer">theming system</a> and <a href="https://v1.vuepress.vuejs.org/plugin/" target="_blank" rel="noopener noreferrer">Plugin API</a>, and a <a href="https://v1.vuepress.vuejs.org/theme/default-theme-config.html" target="_blank" rel="noopener noreferrer">default theme</a> optimized for writing technical documentation. It was created to support the documentation needs of Vue's own sub projects.</p>
<p>Each page generated by VuePress has its own pre-rendered static HTML, providing great loading performance and is SEO-friendly. Once the page is loaded, however, Vue takes over the static content and turns it into a full Single-Page Application (SPA). Additional pages are fetched on demand as the user navigates around the site.</p>
<p>xxxxxxxxxxxxxxxx
<i>888888888888888888</i></p>
<TestComponent></TestComponent><demo-component msg='msg props  of a demo component' /><demo-component msg='msg props  of a demo component' /><CustomLink text="Get Started →" link="/1_wbc-ui2-integration-options" /></div></template>


